[workspace]
resolver = "2"

members = [
    "cli",
    "lib",
    "libs/wasm-loader",
    "libs/wasm-testbed",
    "libs/substrate-runtime-proposal-hash",
    "libs/substrate-differ",
    "libs/ipfs-hasher",
]